### ISSUE TITLE
Dat BLUE though.... :D (Theming?)

### ISSUE THREAD

**Issue by TheShaman** [PhieF/CarnetDocumentation#16]
Hi there! 

After a long odyssey through a gazillion of note taking apps I have finally run into Carnet, which comes pretty close to my way of working with notes and snippets. I like it a lot!

But... but... errrr... I know, aesthetics are a very personal thing... and I do not want to upset the dev of my new favorite notes app... but THAT BLUE is killing me! :dagger: 

It also makes a very decent app look very Microsoft-ish... ;)

Could not find anything in the settings to change the look&feel of the app. 
Is there anything in some config file where we could change the color scheme the app uses?
Or is some kind of "theme" support planned?

People spend a lot of time staring at their notes app, and all the fellow blue-haters of the world would LOVE you if they could change this... 

Cheers! :)

**Comment by PhieF** [comment]
Currently working on a theme feature : 
https://framapiaf.org/@Carnet
(click on images to see them completely, otherwise they are badly cropped)
it will be on next release

I like blue :P  hihi

**Comment by TheShaman** [comment]
Quite obvious that you like blue, :rofl: 

...and nice to see you guys are working on a couple themes! 

Great!

As long as it is light grey, I like it. :stuck_out_tongue:

**Comment by PhieF** [comment]
Dark theme implement, other will come ! :)
