### ISSUE TITLE
Not working anymore after update

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [PhieF/CarnetDocumentation#17]
Just updated to 0.11.0 and it's not working anymore

![a6e7f91e-ee56-4d08-a670-80235caf6484](https://user-images.githubusercontent.com/7016954/50154482-bdf2d180-02c9-11e9-9e99-53f1dfc15271.png)

**Comment by PhieF** [comment]
Thanks for reporting,

What is the issue exactly as a user ? Can you please send me a network tab screenshot ?
Thanks again !

**Comment by ZatsuneNoMokou** [comment]
I guess it is not able to load the list, as it's the exemple ones displayed.

![fd91bc4c-ae37-43a4-8f4c-55f774819712](https://user-images.githubusercontent.com/7016954/50161899-e9c78480-02d4-11e9-9f6c-86139bf81e81.png)
![535b857d-ced2-43ac-a265-cadfa14bdf51](https://user-images.githubusercontent.com/7016954/50161900-ea601b00-02d4-11e9-9970-5a179c2b2002.png)

**Comment by ZatsuneNoMokou** [comment]
And the response of getOrder is :
```json
{"message":"CSRF check failed"}
```

**Comment by ZatsuneNoMokou** [comment]
It get : 
```json
{"data":[]}
```

**Comment by ZatsuneNoMokou** [comment]
I understand the sortable error, but it still might be because of your app, I guess. The page of your app seems to do something with https://apps.nextcloud.com/apps/apporder No idea of what/how

**Comment by ZatsuneNoMokou** [comment]
If I get it well, you load jQuery 1.8.2, but, the core already load jQuery but the version 2.1.4

**Comment by PhieF** [comment]
OK thanks, I will remove it for nextcloud but it doesn't seem to be the error

weird that data is empty, what about "browser" mode ?

**Comment by ZatsuneNoMokou** [comment]
It seems to be working now, there's still some errors in the console, there's one in the settings page 
![image](https://user-images.githubusercontent.com/7016954/50574066-c1fe1380-0de0-11e9-86e2-21b7aec4d17a.png) and on the write page 
![image](https://user-images.githubusercontent.com/7016954/50574076-0f7a8080-0de1-11e9-9912-88211944e401.png). But it seems to be working anyway. Thanks for taking time to fix my issues
