### ISSUE TITLE
Update cycle for the Snap version?

### ISSUE THREAD

**Issue by TheShaman** [PhieF/CarnetDocumentation#18]
Hey guys!

Was eager to have a look at the new version with the dark theme, and the app keeps teasing me that there is a new version available, but when I run "snap refresh" I am told everything is up to date, even when I set Carnet to beta channel. 

Is the Snap edition lagging behind, or which channel should be used to get the latest release?

cheers & merry Christmas!

**Comment by TheShaman** [comment]
Snap version still the same. 

Would appreciate a brief reply, even if it says "We do not do that Snap crap any more" ;)

**Comment by PhieF** [comment]
Well no, the snap is in v12 now, don't you have it ?

Le jeu. 17 janv. 2019 à 23:38, TheShaman <notifications@github.com> a 
écrit :

**Comment by TheShaman** [comment]
whooops, my apologies, 'snap list' indeed reports version 0.12.1 now (must have quietly updated in the last two days since I checked last)

And now it does not start any more.. ROFL

But that might have to do with the sometimes faulty snap implementation on Solus. 
Will check what's the problem and report back.

**Comment by PhieF** [comment]
No problem ! but I've released it... I would say the 31st of December, 
so that's weird !

I had issues to build the snap version

Le jeu. 17 janv. 2019 à 23:51, TheShaman <notifications@github.com> a 
écrit :

**Comment by TheShaman** [comment]
Yeah, don't get me started on snap ... lol

In this case I had to do 
snap disable carnet
snap enable carnet
because it was whining about some permission problems. 

Now it seems to work again! 
Thank you! Solved! :)
