### ISSUE TITLE
Support Joplin

### ISSUE THREAD

**Issue by nr458h** [PhieF/CarnetDocumentation#2]
Hi I like your app.
But as your roadmap and ideas look similar to https://github.com/laurent22/joplin I want to ask you to contribute there. For example with an NC Online app or UI work.

If you want to work on your on app I understand and also want to support because there can't be enough  FOSS-Apps

Thanks for your efforts anyway

**Comment by PhieF** [comment]
Hi !

For now I have plans on my app that I don't use just as a note taking apps, so I will continue to develop it, but why not helping you as well !

**Comment by gerroon** [comment]
It would be nice if the Nextcloud app supports the Joplin notes on the server for sure.

**Comment by nr458h** [comment]
hey as I see that you are heading a different direction than Joplin I close this issue and want to say thank you for shareing your code and time.
