### ISSUE TITLE
"Loading" on Android

### ISSUE THREAD

**Issue by ftastisch** [PhieF/CarnetDocumentation#21]
Hi!

I would like to give Carnet a try as my note taking app, unfortunately when I try to create a note on Android (fdroid version), it just says "Loading" and nothing happens anymore, even if I wait for several minutes.

Best regards,
Fo

**Comment by PhieF** [comment]
hi, which android version are you using ? Thanks !

Le sam. 29 déc. 2018 à 11:41, ftastisch <notifications@github.com> a 
écrit :

**Comment by ftastisch** [comment]
Hi!

Sorry, I forgot: I'm on Android Pie on a Xiaomi A2 lite (--> androidone).

**Comment by ftastisch** [comment]
Oh, and I cannot open a note that created in the nextcloud app either. This also shows a loading screen that does not go away.

**Comment by ftastisch** [comment]
Just installed your update, it's working now... Thanks!
