### ISSUE TITLE
Allow notes to have a date set in addition to default created/modified date

### ISSUE THREAD

**Issue by antonizoon** [PhieF/CarnetDocumentation#22]
I'm hoping to use Carnet as a replacement for the Android App Journey, which aims to make a Markdown based photojournal recording onto cloud storage.

Since journey is both proprietary and uses Google Drive, I was trying Carnet as an alternative, and it is generally a sufficient replacement except for the fact that it does not allow an event date to be set.

Journey allows notes to have an Event Date so I can make notes about a certain time long after it has happened, and then it sorts notes by the Event Date. This is different from the current created/modified date, which can be retained as not modifiable.

In addition, Journey detects the Event Date from photos using exif data. This would also be a great feature to have.

**Comment by PhieF** [comment]
Hi, 

this will be shipped on next version !
Sorry I forgot to answer that :)

the sorting order isn't yet implemented, but it will
