### ISSUE TITLE
Access data base on Linux system

### ISSUE THREAD

**Issue by chkuehnel** [PhieF/CarnetDocumentation#28]
Hi Phief,

first thanks for your work on this beautiful and helpful app!

I want to write a script, that will allow my home automatisation server to open, search in and change my shopping list. 
This will be synched with Nextcloud. This shall be triggered by my Snips instance. 
Could you give me a hint how to access my notes on Raspbian Lite based system?

Thanks 
Christian

**Comment by PhieF** [comment]
Hi

It depends how you use it

if you use it on android, and syncing it on your own nextcloud server, 
then notes are on your nextcloud data folder. If you are using 
carnet.live, try to find either a webdav sync client, or use the 
electron version of carnet... which is quite heavy for a raspberry
once you have if on your raspberry (with electron it will default in 
~/Documents/QuickDoc I guess)
each note is a sqd file which is in reality a zip file.
If you want to add an item in an already created todolist, open the 
metadata.json inside the zip, it will be a json file. Inside the json 
file there is a todolist array
"todolist":[]

a typical todolist will be
"todolist":[{"todo":["item1", "item2'],"done":["item3","item4"], 
"id":"random-small-string"}]

so if you already have a todolist, just complete it



Le jeu. 7 févr. 2019 à 21:46, chkuehnel <notifications@github.com> a 
écrit :

**Comment by chkuehnel** [comment]
thanks, was what i was looking for.
