### ISSUE TITLE
Feature request: unarchive notes

### ISSUE THREAD

**Issue by chepec** [PhieF/CarnetDocumentation#32]
So far I've tested the Carnet webgui (in Nextcloud), the Carnet Android app (from F-droid), and the Carnet desktop app (on Linux). I've even successfully imported hundreds of Google Keep notes. Awesome! You're probably already well aware of this, but I couldn't find any existing issue on the topic, so here goes.

Moving a note from "Recent" to "Browser" works by clicking "Archive" in the note object menu. 
But the apps seem to lack any way to *unarchive* a note (i.e., moving a note back from "Browser" to "Recent"). Perhaps this should be added to the note object menu? Or is that achieved by pinning (but isn't that a different concept)?

Closely related to this, the naming here is a bit confusing. Archiving something moves it to "Browser". So why not rename "Browser" to "Archive"? Or am I misunderstanding your intentions? :-)

**Comment by PhieF** [comment]
Hi,

In fact, archiving doesn't move to browser but remove from recent, but I understand your point. On Android it's "remove from recent", that's better
The unarchive function is on its way

**Comment by chepec** [comment]
Thanks for that clarification and the news.  

And I really appreciate your efforts on Carnet! I'm using it daily, and it works reliably across multiple computers and multiple devices.

**Comment by PhieF** [comment]
Thanks !

Now implemented ! :)
