### ISSUE TITLE
Need french translation for Desktop

### ISSUE THREAD

**Issue by alexsourcerer** [PhieF/CarnetDocumentation#33]
Carnet is only in english on the desktop version.
I could translate it in french in needed. It would integrate more for french users of the desktop version.

**Comment by PhieF** [comment]
Hi, just an update to say that translations are on their way to the desktop version. French translations will be easy since I'm French ! but if you know another language you can help here

https://weblate.lostpod.me/projects/carnethtml/

Thanks ! :)
