### ISSUE TITLE
Any plans for an iOS app?

### ISSUE THREAD

**Issue by loup-brun** [PhieF/CarnetDocumentation#37]
The title pretty much says it all.

**Comment by loup-brun** [comment]
(I would like to connect Carnet with my Nextcloud instance)

**Comment by PhieF** [comment]
I'm afraid it would require too much work :( have you tried the web version on your idevice, like this server

https://carnet.live ?

Usually on iPhones you can add this as a screenshot on the homepage

**Comment by loup-brun** [comment]
The web version is working pretty well on iPhone :) The screen is pretty small, but it's more about the device itself, so I won't complain…

Anyway, was just wondering whether the project was going to be ported for iOS or not. Thanks! 😀
