### ISSUE TITLE
Readme link to roadmap is unavailable

### ISSUE THREAD

**Issue by almereyda** [PhieF/CarnetDocumentation#39]
The readme presents a headline

> To come
>
> [See here](https://github.com/PhieF/CarnetDocumentation/blob/master/FUTURE.md)

that links to `https://github.com/PhieF/CarnetDocumentation/blob/master/FUTURE.md`.

Following this file yields a 404.

This file was renamed in https://github.com/PhieF/CarnetDocumentation/commit/9703d26640a2561b4d2cb53f63cdd6d89784e33a#diff-c4a457a5e966311827afc343d0606e58 and https://github.com/PhieF/CarnetDocumentation/commit/d52f2b22d93e7e12f5ca829ec28ff56624e7a01b to `TODO.md`.

**Comment by PhieF** [comment]
Thanks for the report !
Fixed ;)
