### ISSUE TITLE
Add Czech language to weblate

### ISSUE THREAD

**Issue by leschek** [PhieF/CarnetDocumentation#41]
Not sure if this is correct place, but could you add the Czech language to weblate, please? I would like to translate Carnet, but it seems I can't to add it myself.

**Comment by PhieF** [comment]
Hi

even when you're logged in Weblate ? 
Thanks for this :)

**Comment by leschek** [comment]
Well, I found there on Weblate this: "Only languages which are currently being translated are listed. If you want to translate to another language, please request it first on the project you want to translate."

**Comment by PhieF** [comment]
Even when you go here, after login

https://weblate.lostpod.me/projects/carnethtml/android/

you don't have "start new translation" ?

Weird, it should be there

**Comment by leschek** [comment]
Thanks. Now I found it. I thought there would be such button for the whole project in language tab. I didn't look into subfolders. Sorry.

**Comment by PhieF** [comment]
Yes sorry for that, it has to be created into each version...

Thanks for the translations !
