### ISSUE TITLE
Notes dissapear after app update in Nextcloud

### ISSUE THREAD

**Issue by wouterVE** [PhieF/CarnetDocumentation#43]
Hi,
I've encountered several times that after an update of the Carnet app in Nextcloud, all of my previous notes are gone. 
The folder in which the notes are saved (Documents/Quicknote) is emptied indeed.

Probably this has something to do with the 'fake notes' that are shown after each update of the app? I would suggest to remove this feature as this is confusing anyways, only interesting after the first installation in my opinion. 

If in need for any help/info I'm glad to provide you.

kr
wouter

**Comment by PhieF** [comment]
Hm It shouldn't happen, these notes are displayed only when no notes are found
are you sure your notes are being deleted ? I don't see any part of the code that could lead to this problem

**Comment by wouterVE** [comment]
I've found some details deleted notes in my delrted files folder, but unfortunately these were not the notes that I was looking for. It occurred 2 times that I've lost my notes in Nextcloud, the first time in the nextcloud of my company and second time in my private nextcloud. If i'll find time this week, I'll try to perform a manual update and see wether te notes are gone or not.

I'll keep you informed. 

Kr
Wouter

**Comment by wouterVE** [comment]
Hi,
Update on this 'issue'. It appeares it's not due to Carnet's fault. I've noticed that from time to time, the folder ~/Documents/Quicknote (in which Carnet saves the notes) is moved to recycle bin. So apparantly, Carnet had nothing to do with it. 

But just to make sure, is there some 'audit' I can perform on this folder to see which process is moving this folder to the recycle bin? 
FYI: I'm running Nextcloud 15.0.2 on Armbian (=based on debian 9).

kr
wouter

**Comment by wouterVE** [comment]
Hi,
I'll close this issue as it was never an issue from carnet self. After some Nextcloud updates I've never encountered this again. 

kr 
wouter
