### ISSUE TITLE
Linux App crash when creating a note

### ISSUE THREAD

**Issue by JokerGermany** [PhieF/CarnetDocumentation#51]
Version:
Ubuntu 18.04.2 64 Bit
carnet 0.13.0 
Server Version:   0.15.6

What i have done:
install snap version (Error occurs even with the AppImage)
Tried to make a note.
insert text into the note

Error window:
`A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at /snap/carnet/7/resources/app.asar/server/server.js:485:30
    at FSReqWrap.oncomplete (fs.js:183:5)`
`

I done everything in a terminal to track down error messages:
`sudo snap uninstall carnet
Fehler: unknown command "uninstall", see 'snap help'.`

`sudo snap remove carnet
carnet entfernt`

`sudo snap install carnet
carnet 0.13.0 aus Alexandre Roux (alexandre-roux-m) installiert`

`carnet
Gtk-Message: Failed to load module "appmenu-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
app uid af83a9ca-8720-8fcc
setting sync to 10 minutes
hasDownloadedSmt false
app uid af83a9ca-8720-8fcc
merge finished has changed ? false
merge finished has changed ? false`

`carnet
Gtk-Message: Failed to load module "appmenu-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
app uid af83a9ca-8720-8fcc
app uid af83a9ca-8720-8fcc
visit ok 3
added to cache Todo.sqd
added to cache asdassa.sqd
merge finished has changed ? false
merge finished has changed ? false
added to cache untitled 2Msa.sqd
added to cache untitled 3S.sqd
added to cache untitled 4H.sqd
added to cache untitledK.sqd
setting sync to 10 minutes
hasDownloadedSmt true
merge finished has changed ? true
merge finished has changed ? false
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`

**Comment by mantaboo** [comment]
I have the same problem with carnet-0.13.0-1 on Arch Linux.

**Comment by PhieF** [comment]
Hi, I'm working on it right now :) 

thanks for the report
