### ISSUE TITLE
Possible Sync Issues leading to login issues & corrupted notes - Android 0.19.0/Nextcloud 0.19.1 

### ISSUE THREAD

**Issue by timbogithub** [PhieF/CarnetDocumentation#87]
Hello all

Since the upgrade to Android 0.19.0, I have encountered several issues:

1. Android app constantly opens welcome screen and asks for credentials, even though Accounts list multiple same accounts.
2. Background sync notification becomes non responsive - toast notification remains and cannot be swiped away. (Battery optimization is disabled)
3. Note titles in "Browser" have become corrupted, adding long numbers to them, all beginning with 15780. Content of notes in Browser is unaffected, thankfully. 
4. "Latest" picture notes contains titles of notes, but no pictures. 

![image](https://user-images.githubusercontent.com/49436768/71766857-94204300-2efc-11ea-8f9f-40d5b99c632c.png)

Have reinstalled Android app but the issue persists - corruption has been synced.  I will manually adjust but this worries me - I have come to rely on Carnet, and am now concerned that all my notes will be lost. 

Thanks

**Comment by PhieF** [comment]
This issue of welcome screen should be fixed, can you try with the latest android app ? Thank

**Comment by PhieF** [comment]
If you still have the issue, you can ask me to reopen the issue
